language: node_js
sudo: false
node_js:
  - "10.0"

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g grunt-cli

script:
  - grunt travis
